name: DiscordBot
version: 1.0.0
main: pink.cutezy.DiscordBot.DiscordPlugin
softdepend:
  -
  - Factions
  - Towny
authors: [cutezyash]
website: cutezy.pink
commands:
  afk:
    description: Lets you afk/un-afk